List<String> communities = [
  'Flutter Developers',
  'Machine Learning Enthusiasts',
  'Web Developers Network',
  'AI Innovators',
  'Mobile App Builders',
  'Open Source Contributors',
  'Dart Coders',
  'IoT and Robotics',
  'Data Science Society',
  'Blockchain Developers',
  'Python Programmers',
  'Software Engineering Community',
  'Tech Startups Network',
  'Cybersecurity Hub',
  'JavaScript Ninjas',
  'Creative Coders',
  'Women in Tech',
  'Cloud Computing Group',
  'UX/UI Designers',
  'Tech Bloggers',
  'Virtual Reality Explorers',
  'Game Developers Guild',
  'Big Data Analysts',
  'Digital Marketing Hub',
  'Networking Professionals',
  'Freelance Developers',
  'Startup Founders',
  'Augmented Reality Enthusiasts',
  'DevOps Engineers',
  'Innovation and Entrepreneurship'
];
